---

- name: remove downloaded files and extracted directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ mailarchiva_download_dir }}"
    - "/tmp/{{ mailarchiva_latest_version_filename.stdout | trim }}"
