---

- name: Ask Mailarchiva, what's the latest version available
  shell: echo 'ls -t mailarchiva_server_linux*' | sshpass -p fl0w3r sftp -oBatchMode=no enterprise@mailarchiva.com | grep -v "sftp>" | head -n1
  register: mailarchiva_latest_version_filename
  changed_when: false

- name: Extract the version to later determine if the version already installed needs to be updated
  shell: echo "{{ mailarchiva_latest_version_filename.stdout }}" | sed -e "s/^mailarchiva_server_linux_v//" -e "s///" | sed -e "s/.tar.gz//" -e "s///"
  register: mailarchiva_latest_version_number
  changed_when: false

- name: Check if Mailarchiva is already installed on the remote host
  stat:
    path: /var/opt/mailarchiva/tomcat/webapps/ROOT/WEB-INF/classes/version.conf
  register: stat_result

- debug:
#    msg: "{{ mailarchiva_download_dir }}/mailarchiva/server/webapps/ROOT"
    var: stat_result.stat

- import_tasks: install.yml
  when: stat_result.stat.exists == False

- import_tasks: update.yml
  when: stat_result.stat.exists == True
