---

- name: Extract the version to later determine if the version already installed needs to be updated
  slurp:
    src: /var/opt/mailarchiva/tomcat/webapps/ROOT/WEB-INF/classes/version.conf
  register: mailarchiva_current_version_number

- set_fact:
    mailarchiva_current_version_number_clean: "{{ mailarchiva_current_version_number['content'] | b64decode | trim }}"
#    mailarchiva_latest_version_number_clean:  "{{ mailarchiva_latest_version_number.stdout | trim }}"

- set_fact:
    current_version_needs_to_be_udapted : "{{ 'False' if mailarchiva_current_version_number_clean == mailarchiva_latest_version_number_clean else 'True' }}"

- block:
    - name: "End play if nothing to upgrade"
      debug:
        msg: "nothing to upgrade, ending play"

    - meta: end_host
  when:
    - current_version_needs_to_be_udapted == False

- import_tasks: download.yml
  when: current_version_needs_to_be_udapted == True

- import_tasks: cleanup.yml
  when: current_version_needs_to_be_udapted == True
